name: MSYS2
on: [push, pull_request]

jobs:
  msys2-mingw64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git autotools mingw-w64-x86_64-meson gcc gettext-devel glib2-devel mingw-w64-x86_64-gobject-introspection
      - name: Install Bubblewrap
        run: |
          git clone https://github.com/containers/bubblewrap
          cd bubblewrap
          meson _build
          meson compile -C _build
          meson install -C _build
      - name: Build Flatpak
        run: |
          git clone https://github.com/flatpak/flatpak
          cd flatpak
          NOCONFIGURE=1 ./autogen.sh
          ./configure --prefix=/usr --sysconfdir=/etc --libdir=/usr/lib64 --localstatedir=/var --enable-docbook-docs --enable-installed-tests --enable-selinux-module --with-system-bubblewrap --with-system-dbus-proxy
          make -j$(nproc)
          make check -j$(nproc)
          make install
