name: MSYS2
on: [push, pull_request]

jobs:
  msys2-mingw64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-cc
      - uses: actions/checkout@v3
        with:
          repository: flatpak/flatpak
      - name: CI-Build
        run: |
          NOCONFIGURE=1 ./autogen.sh
          ./configure --prefix=/usr --sysconfdir=/etc --libdir=/usr/lib64 --localstatedir=/var --enable-docbook-docs --enable-installed-tests --enable-selinux-module --with-system-bubblewrap --with-system-dbus-proxy
          make -j$(nproc)
          make check -j$(nproc)
          make install
